### ISSUE TITLE
pymol: error: no member named 'signbit' in the global namespace [macOS 10.15 Catalina]

### ISSUE THREAD

**Issue by luwei0917** [brewsci/homebrew-bio#1005]
I tried brew doctor. but still not working.
I'm using Mac 10.15.5 Beta (19F62f), maybe this is the problem.
I've been googling for more than 2 hour. But no luck. 

Here is the gist-log 
https://gist.github.com/0f374e0e4ad2e5d8033a921e1da8be07

Please help.
Thanks a lot.

**Comment by sjackman** [comment]
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
```
https://gist.githubusercontent.com/luwei0917/0f374e0e4ad2e5d8033a921e1da8be07/raw/02536cbc335d3addb578171dc339c7c69dad36ad/08.python3

This error looks like an issue building Pymol with a modern macOS. Would you like to open an issue upstream and link to that issue here?
https://github.com/schrodinger/pymol-open-source/issues

**Comment by sjackman** [comment]
I've just tested `brew install pymol` on macOS 10.14 Mojave, and it worked fine. I suspect that this error is specific to macOS 10.15 Catalina. Two possible workarounds for you are to use a macOS 10.14 machine if you have access to one. Try installing `pymol` using GCC instead of Apple Clang. I haven't tried this yet.
```bash
brew install gcc
brew install pymol --cc=gcc-9
```

**Comment by luwei0917** [comment]
Thanks. I'm able to install without any problem after upgrading(or downgrading) the system to macOS 10.15.4 from the 10.15.5 beta.

**Comment by sjackman** [comment]
Oh, great. Glad to hear it. I also built a bottle for macOS on macOS 10.14 Mojave, so you don't have to build from source now.
