### ISSUE TITLE
Emboss Packages failed to install 

### ISSUE THREAD

**Issue by bioinfo-Kacst** [brewsci/homebrew-bio#1135]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
trying to install EMBOSS packages in my server computer
- What happened (include command output)
```
brew install emboss
Updating Homebrew...
==> Installing emboss from brewsci/bio
==> Downloading ftp://emboss.open-bio.org/pub/EMBOSS/EMBOSS-6.6.0.tar.gz
Already downloaded: /lustre/mohanad/.cache/Homebrew/downloads/96cd20fa32c7065e96a813ca62f2bc652fee9061a40baf7481571b6f7feea0fb--EMBOSS-6.6.0.tar.gz
==> ./configure --prefix=/lustre/mohanad/.linuxbrew/Cellar/emboss/6.6.0 --mandir=/lustre/mohanad/.linuxbrew/Cellar/emboss/6.6.0/share/man --docdir=/lustre/mohanad/.linuxbrew/Cellar/
==> make install
Last 15 lines from /lustre/mohanad/.cache/Homebrew/Logs/emboss/02.make:
make[2]: Nothing to be done for `install-data-am'.
make[3]: Entering directory `/tmp/emboss-20200812-2863-1a98qsp/EMBOSS-6.6.0'
/lustre/mohanad/.linuxbrew/Cellar/emboss/6.6.0/bin/embossupdate
Check for more recent updates to EMBOSS
Error: [Temporary failure in name resolution] Failed to find host 'emboss.open-bio.org' for database 'EMBOSSupdates'
Error: ajHttpRead: cannot open HTTP connection 'http://emboss.open-bio.org/updates/EMBOSS.fixes'
Died: Failed to read 'http://emboss.open-bio.org/updates/EMBOSS.fixes'
EMBOSS release 6.6.0.0: update information not available
make[3]: *** [install-exec-hook] Error 1
make[3]: Leaving directory `/tmp/emboss-20200812-2863-1a98qsp/EMBOSS-6.6.0'
make[2]: *** [install-exec-am] Error 2
make[2]: Leaving directory `/tmp/emboss-20200812-2863-1a98qsp/EMBOSS-6.6.0'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/tmp/emboss-20200812-2863-1a98qsp/EMBOSS-6.6.0'
make: *** [install-recursive] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/brewsci/homebrew-bio/issues

```
- What you expected to happen
To be installed 
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `emboss`.
Another possible workaround for you is `brew install --force-bottle emboss`, but no promises.

If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
```
Check for more recent updates to EMBOSS
Error: [Temporary failure in name resolution] Failed to find host 'emboss.open-bio.org' for database 'EMBOSSupdates'
Error: ajHttpRead: cannot open HTTP connection 'http://emboss.open-bio.org/updates/EMBOSS.fixes'
Died: Failed to read 'http://emboss.open-bio.org/updates/EMBOSS.fixes'
EMBOSS release 6.6.0.0: update information not available
```

Your error building from source was due to a hopefully transient network failure. Try again.
