### ISSUE TITLE
current clipper, coot etc for M1

### ISSUE THREAD

**Issue by wgscott** [brewsci/homebrew-bio#1297]
I maintain clipper and coot and a few others for fink, but Homebrew is significantly ahead of fink for the latest OS and M1 platform.  I have clipper, mmdb2, ssm, libccp4, etc compiling on M1 with gcc/gfortran 10.  I am working with Paul Emsley trying to get the latest coot with gtk+3 and python3.9 working.  coot compiles, but the (non-X11) gtk+3 GUI freezes while loading, so I have a bit more work to do (and could use some help).  In any case, I would be happy to help contribute to any of the above-named packages (or any others that I maintain for fink).

**Comment by YoshitakaMo** [comment]
Thanks, @wgscott. Your offer is very encouraging. As you've already noticed, I am planning to create a Homebrew formula of the latest version of Coot, especially one with gtk+3 GUI. Recently, I made `rdKit` formula for this purpose, which has been merged into Homebrew-core recently ( https://github.com/Homebrew/homebrew-core/pull/71694 ). Now I'm building `coot-gtk3` Formula on https://github.com/YoshitakaMo/homebrew-bio/blob/coot/Formula/coot.rb , but it does't work well yet.

I have succeeded in building and installing the Coot-gtk3 branch manually on my Mac (macOS Big Sur 11.2.1), but the installation fails when using the Formula described above. Also, although the manually-installed Coot-gtk3 could boot (with a lot of warning messages), it can't display molecules properly, and always causes Segmentation Fault when terminating Coot. I don't know how to solve this problem.

If you have an interest, you can also try to install it using the following command (but it fails):

```
wget https://raw.githubusercontent.com/YoshitakaMo/homebrew-bio/coot/Formula/coot.rb
brew install ./coot.rb --verbose --HEAD
```

I'm also concerned about installation of the current stable version, but I've not tried it yet because it may require legacy guile-gtk or etc..

I will appreciate your suggestions or comments. Let's work together to create a Homebrew Formula for Coot!
