### ISSUE TITLE
The bottles are currently unavailable

### ISSUE THREAD

**Issue by YoshitakaMo** [brewsci/homebrew-bio#1327]
The homebrew-bio's bottles have been unavailable since a couple of days. The cause is probably described in https://archive.org/download/brewsci/bottles-bio/.

> Items may be taken down for various reasons, including by decision of the uploader or due to a violation of our Terms of Use.

Please check it, @sjackman .

**Comment by sjackman** [comment]
This issue has already been reported to the Internet Archive, and we're waiting for them to respond.

If you need a workaround in the mean time, you can install from source (easiest) or install from the bottles that are still on Bintray. https://linuxbrew.bintray.com/bottles-bio/

To install a single bottle, copy-and-paste the URL to the bottle and
`brew install https://linuxbrew.bintray.com/bottles-bio/:ntcard-1.2.2.x86_64_linux.bottle.tar.gz`

To install many bottles from Bintray, change the `root_url` to Bintray:
`gsed -i 's~root_url.*~root_url "https://linuxbrew.bintray.com/bottles-bio"~' $(brew --repo brewsci/bio)/Formula/*.rb`

On Linux `sed -i '/root_url/d' $(brew --repo brewsci/bio)/Formula/*.rb` also works, because `HOMEBREW_BOTTLE_DOMAIN=https://linuxbrew.bintray.com` is the default on Linux.

**Comment by sjackman** [comment]
The Brewsci bottles are being migrated to GitHub Packages, which will prevent this particular issue in the future.

**Comment by sjackman** [comment]
Bottles of 296 formulae (93%) have been migrated from Bintray to GitHub Packages.
Bottles of 23 formulae (7%) are waiting for Archive.org to come back online, so their bottles can be downloaded, and uploaded to GitHub Packages.

**Comment by sjackman** [comment]
https://archive.org/details/brewsci is back online. This issue is resolved.

**Comment by sjackman** [comment]
All bottles have been migrated from Bintray to GitHub Packages.
